version: '3.8'

services:
  firebase:
    image: andreysenov/firebase-tools
    container_name: firebase-emulator
    ports:
      - "4000:4000" # Emulator UI
      - "8080:8080" # Cloud Functions
      - "9000:9000" # Realtime Database
      - "9099:9099" # Authentication
      - "9199:9199" # Storage
    volumes:
      - ./firebase:/home/node/app
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    command: firebase emulators:start --project nomnom-103d6

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_DATABASE_URL=${NEXT_PUBLIC_FIREBASE_DATABASE_URL}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_FIREBASE_API=http://localhost:3000/api
    depends_on:
      - firebase
    command: npm run dev

volumes:
  postgres_data:


networks:
  default:
    driver: bridge
